---
name: "OpenTofu"

#on:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [ main ]

jobs:
  opentofu:
    name: "OpenTofu"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Format
        run: tofu fmt -check

      - name: OpenTofu Plan
        run: tofu plan -no-color
        continue-on-error: true

      - name: OpenTofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve
